import { describe, it, expect } from 'vitest';
import { compileRExportPattern } from '../../src/core/ingestion/languages/r/export-pattern.js';

// Names every characterisation row is evaluated against.
const NAMES: readonly string[] = [
  'tidy_scores',
  '.hidden',
  'foo_bar',
  'bar_baz',
  'foo',
  'bar',
  'a',
  'aa',
  'aaa',
  'aaaa',
  'abc',
  'ac',
  'Abc',
  'A1_b',
  'print.foo',
  'getX',
  'setY',
  'x',
  '',
  '_x',
  '1a',
  'foo.',
  'a.c',
  'a{,2}',
  'a{',
  'a|b',
  '[',
  'a]',
  ']',
  'foo$',
  'my_internal',
  'x.y',
  'aaab',
  'ab',
];

// [exportPattern source, names from NAMES it matches]. Recorded from the original
// backtracking-RegExp implementation, so this table pins behaviour that must not change.
const CHARACTERISATION: ReadonlyArray<readonly [string, readonly string[] | null]> = [
  [
    '^[[:alpha:]]+',
    [
      'tidy_scores',
      'foo_bar',
      'bar_baz',
      'foo',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      'print.foo',
      'getX',
      'setY',
      'x',
      'foo.',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      'a]',
      'foo$',
      'my_internal',
      'x.y',
      'aaab',
      'ab',
    ],
  ],
  [
    '^[^\\.]',
    [
      'tidy_scores',
      'foo_bar',
      'bar_baz',
      'foo',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      'print.foo',
      'getX',
      'setY',
      'x',
      '_x',
      '1a',
      'foo.',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      '[',
      'a]',
      ']',
      'foo$',
      'my_internal',
      'x.y',
      'aaab',
      'ab',
    ],
  ],
  ['^(foo|bar)_', ['foo_bar', 'bar_baz']],
  [
    '.',
    [
      'tidy_scores',
      '.hidden',
      'foo_bar',
      'bar_baz',
      'foo',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      'print.foo',
      'getX',
      'setY',
      'x',
      '_x',
      '1a',
      'foo.',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      '[',
      'a]',
      ']',
      'foo$',
      'my_internal',
      'x.y',
      'aaab',
      'ab',
    ],
  ],
  [
    '^',
    [
      'tidy_scores',
      '.hidden',
      'foo_bar',
      'bar_baz',
      'foo',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      'print.foo',
      'getX',
      'setY',
      'x',
      '',
      '_x',
      '1a',
      'foo.',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      '[',
      'a]',
      ']',
      'foo$',
      'my_internal',
      'x.y',
      'aaab',
      'ab',
    ],
  ],
  [
    '$',
    [
      'tidy_scores',
      '.hidden',
      'foo_bar',
      'bar_baz',
      'foo',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      'print.foo',
      'getX',
      'setY',
      'x',
      '',
      '_x',
      '1a',
      'foo.',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      '[',
      'a]',
      ']',
      'foo$',
      'my_internal',
      'x.y',
      'aaab',
      'ab',
    ],
  ],
  [
    '',
    [
      'tidy_scores',
      '.hidden',
      'foo_bar',
      'bar_baz',
      'foo',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      'print.foo',
      'getX',
      'setY',
      'x',
      '',
      '_x',
      '1a',
      'foo.',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      '[',
      'a]',
      ']',
      'foo$',
      'my_internal',
      'x.y',
      'aaab',
      'ab',
    ],
  ],
  ['foo', ['foo_bar', 'foo', 'print.foo', 'foo.', 'foo$']],
  ['^foo', ['foo_bar', 'foo', 'foo.', 'foo$']],
  ['foo$', ['foo', 'print.foo']],
  ['^foo$', ['foo']],
  [
    'a|b',
    [
      'foo_bar',
      'bar_baz',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      '1a',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      'a]',
      'my_internal',
      'aaab',
      'ab',
    ],
  ],
  ['^(a|b)c', ['ac']],
  [
    '[abc]',
    [
      'tidy_scores',
      'foo_bar',
      'bar_baz',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      '1a',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      'a]',
      'my_internal',
      'aaab',
      'ab',
    ],
  ],
  [
    '[^abc]',
    [
      'tidy_scores',
      '.hidden',
      'foo_bar',
      'bar_baz',
      'foo',
      'bar',
      'Abc',
      'A1_b',
      'print.foo',
      'getX',
      'setY',
      'x',
      '_x',
      '1a',
      'foo.',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      '[',
      'a]',
      ']',
      'foo$',
      'my_internal',
      'x.y',
    ],
  ],
  ['^[a-z]+$', ['foo', 'bar', 'a', 'aa', 'aaa', 'aaaa', 'abc', 'ac', 'x', 'aaab', 'ab']],
  ['^[[:upper:]][[:alnum:]_]*$', ['Abc', 'A1_b']],
  [
    '^[[:alpha:].]+$',
    [
      '.hidden',
      'foo',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'print.foo',
      'getX',
      'setY',
      'x',
      'foo.',
      'a.c',
      'x.y',
      'aaab',
      'ab',
    ],
  ],
  ['\\.', ['.hidden', 'print.foo', 'foo.', 'a.c', 'x.y']],
  ['^\\.', ['.hidden']],
  ['^[.]', ['.hidden']],
  ['^(?:foo|bar)', ['foo_bar', 'bar_baz', 'foo', 'bar', 'foo.', 'foo$']],
  [
    'x?',
    [
      'tidy_scores',
      '.hidden',
      'foo_bar',
      'bar_baz',
      'foo',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      'print.foo',
      'getX',
      'setY',
      'x',
      '',
      '_x',
      '1a',
      'foo.',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      '[',
      'a]',
      ']',
      'foo$',
      'my_internal',
      'x.y',
      'aaab',
      'ab',
    ],
  ],
  ['a{2,3}', ['aa', 'aaa', 'aaaa', 'aaab']],
  ['^a{2}$', ['aa']],
  [
    '^\\w+$',
    [
      'tidy_scores',
      'foo_bar',
      'bar_baz',
      'foo',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      'getX',
      'setY',
      'x',
      '_x',
      '1a',
      'my_internal',
      'aaab',
      'ab',
    ],
  ],
  ['^\\d', ['1a']],
  ['\\bfoo\\b', ['foo', 'print.foo', 'foo.', 'foo$']],
  [
    '^[[:alpha:]][[:alnum:]._]*$',
    [
      'tidy_scores',
      'foo_bar',
      'bar_baz',
      'foo',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      'Abc',
      'A1_b',
      'print.foo',
      'getX',
      'setY',
      'x',
      'foo.',
      'a.c',
      'my_internal',
      'x.y',
      'aaab',
      'ab',
    ],
  ],
  ['^print\\.', ['print.foo']],
  ['^(get|set)[A-Z]', ['getX', 'setY']],
  ['a.c', ['abc', 'a.c']],
  ['^.{3}$', ['foo', 'bar', 'aaa', 'abc', 'Abc', 'a.c', 'a|b', 'x.y']],
  ['[]a]', []],
  ['[^]a]', []],
  ['^[\\]]', [']']],
  [
    'a+?',
    [
      'foo_bar',
      'bar_baz',
      'bar',
      'a',
      'aa',
      'aaa',
      'aaaa',
      'abc',
      'ac',
      '1a',
      'a.c',
      'a{,2}',
      'a{',
      'a|b',
      'a]',
      'my_internal',
      'aaab',
      'ab',
    ],
  ],
  ['a{,2}', ['a{,2}']],
  ['a{', ['a{,2}', 'a{']],
  ['^[[:punct:]]', ['.hidden', '_x', '[', ']']],
  ['^.*_internal$', ['my_internal']],
  ['^[A-Z]', ['Abc', 'A1_b']],
  ['\\$', ['foo$']],
  ['a\\|b', ['a|b']],
  ['^(a+)+$', ['a', 'aa', 'aaa', 'aaaa']],
  ['^(a|a)+$', ['a', 'aa', 'aaa', 'aaaa']],
  ['^(a*)*b', ['bar_baz', 'bar', 'abc', 'aaab', 'ab']],
  ['^[[:digit:]a-c_]+$', ['a', 'aa', 'aaa', 'aaaa', 'abc', 'ac', '1a', 'aaab', 'ab']],
];

describe('compileRExportPattern characterisation', () => {
  it.each(CHARACTERISATION)('pattern %s keeps its recorded matches', (pattern, expected) => {
    const matcher = compileRExportPattern(pattern);
    if (expected === null) {
      expect(matcher).toBeNull();
      return;
    }
    expect(matcher).not.toBeNull();
    expect(NAMES.filter((n) => matcher?.test(n) === true)).toEqual(expected);
  });
});

// Differential check against the JavaScript RegExp the matcher replaced. Patterns are
// built from a fixed atom list by a seeded generator, so the corpus is deterministic.
// Names are short enough that even a catastrophic generated pattern finishes instantly
// on the oracle.
describe('compileRExportPattern agrees with RegExp on generated patterns', () => {
  const ATOMS = [
    'a',
    'b',
    '1',
    '_',
    '\\.',
    '.',
    '[ab]',
    '[^a]',
    '[a-c]',
    '[^.]',
    '(?:$)',
    '(\\b)',
    '[a.]',
    '\\d',
    '\\w',
    '\\s',
    '\\D',
    '\\W',
    '\\b',
    '\\B',
    '^',
    '$',
    '(',
    '(?:',
    ')',
    '|',
    '*',
    '+',
    '?',
    '{2}',
    '{1,2}',
    '{2,}',
    '{,1}',
    '{',
    '}',
    '*?',
    '+?',
    '??',
    '{1,2}?',
    '[',
    ']',
    '[]',
    '\\x61',
    '\\u0062',
    '\\t',
    '\\-',
    '[\\d-z]',
    '[z-a]',
  ];
  const NAME_ALPHABET = ['a', 'b', '1', '_', '.', ' ', 'c', '\t'];

  function lcg(seed: number): () => number {
    let state = seed >>> 0;
    return () => {
      state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
      return state / 0x100000000;
    };
  }

  it('returns the same verdict, or null exactly when RegExp rejects the source', () => {
    const rand = lcg(20260930);
    const pick = <T>(xs: readonly T[]): T => xs[Math.floor(rand() * xs.length)];
    const names: string[] = [''];
    for (let i = 0; i < 60; i++) {
      const len = Math.floor(rand() * 6);
      let n = '';
      for (let j = 0; j < len; j++) n += pick(NAME_ALPHABET);
      names.push(n);
    }
    let compiled = 0;
    let rejected = 0;
    for (let i = 0; i < 4000; i++) {
      const parts = Math.floor(rand() * 7) + 1;
      let source = '';
      for (let j = 0; j < parts; j++) source += pick(ATOMS);
      let oracle: RegExp | null = null;
      try {
        oracle = new RegExp(source);
      } catch {
        oracle = null;
      }
      const matcher = compileRExportPattern(source);
      if (oracle === null) {
        expect(matcher, `source ${JSON.stringify(source)} is invalid for RegExp`).toBeNull();
        rejected++;
        continue;
      }
      expect(matcher, `source ${JSON.stringify(source)} is valid for RegExp`).not.toBeNull();
      compiled++;
      for (const name of names) {
        expect(matcher?.test(name), `${JSON.stringify(source)} vs ${JSON.stringify(name)}`).toBe(
          oracle.test(name),
        );
      }
    }
    // The corpus must exercise both branches, or the comparison proves nothing.
    expect(compiled).toBeGreaterThan(500);
    expect(rejected).toBeGreaterThan(500);
  });
});
